### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Zitrax** [ldtp/cobra#17]
While working on #15 I noticed the error in the title of this issue when I built from master. The latest binary using installer 4.0.0 did not show that error.

This happens when I do a call to: `ldtp.selectitem(...)`.

I ran a bisect and got this:

*There are only 'skip'ped commits left to test.
The first bad commit could be any of:
3a912d39c5689b8ccde828049b5f71a9fcd3819d
ef33a2654db3d92667688387762ebf906a16cb9e
99732f5c0f3a5a6a699872606bd1612bca952ed5
We cannot bisect more!*

Two of those commits didn't build that's why it only narrowed it down to three.

**Comment by Zitrax** [comment]
The actual traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\client.py", line 72, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\lib\xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\client.py", line 193, in request
    raise LdtpExecutionError(e.faultString.encode('utf-8'))
ldtp.client_exception.LdtpExecutionError: Unhandled exception: Object reference not set to an instance of an object.
```

**Comment by nagappan** [comment]
Can you try this ?

In a terminal:
set LDTP_DEBUG=1
cobrawinldtp.exe

From python prompt:

ldtp.selectitem(...)

You can find the traces on first console why it failed. Thanks

**Comment by Zitrax** [comment]
Log ends with:

```
:InternalGetObjectHandle: Child handle NULL
:System.NullReferenceException: Object reference not set to an instance of an object.
   at Ldtpd.Combobox.InternalComboHandler(String windowName, String objName, String item, String& selectedItem, String a
ctionType, ArrayList childList)
```

So although the rest of the log did not immediately tell me anything this points to Combobox.cs, the only commit of the three above that touches it is ef33a26, and indeed if I revert that single commit it works again.

**Comment by Zitrax** [comment]
I think I see the issue, that commit used `comboTtype` on line 262. Changing that to `type` solves my problem. I can submit a pull request for that.

**Comment by nagappan** [comment]
Great thanks checking.

**Comment by Zitrax** [comment]
By the way is there any plan on adding a new binary release ? The last one seem to be from Nov 2013.

**Comment by Zitrax** [comment]
And unfortunately it turns out my patch above did not really solve this problem - I must have missed something since the problem reappeared now. I tried to reproduce again, and it was definitely the introduced in the earlier mentioned commit.

Further trying to narrow it down showed that it was a LogMessage call this time that seemed to cause this:

```
LogMessage("elementItem: " + elementItem.Current.Name +
                    " - " + elementItem.Current.ControlType.ProgrammaticName);
```

it also happens if I replace that log call with anything that use `elementItem.Current`. Seem a bit odd, but as of now I can reproduce this consistently, comment out those two lines and it works put them back again and it fails. So either the use of that has some direct side effect or there is something weirder going on like a timing issue.

Any ideas ?

**Comment by stilok2** [comment]
I'm getting this error while using getcombovalue method.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\client.py", line 73, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\lib\xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\client.py", line 194, in request
    raise LdtpExecutionError(e.faultString.encode('utf-8'))
ldtp.client_exception.LdtpExecutionError: Unhandled exception: Object reference not set to an instance of an object.

Has this been resolved? Or am I pointing to the wrong binary? Thanks for the help
