### ISSUE TITLE
Import issues with Python 3

### ISSUE THREAD

**Issue by joshsleeper** [ldtp/cobra#21]
With Python 2.7.10 I can simply write `import ldtp` and things work fine.
However, with Python 3.3.5 and 3.4.3 (the versions I tested) I have to manually launch CobraWinLDTP.exe before I import, otherwise it gives me the following error:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\client.py", line 144, in request
    h=self.send_request(host, handler, request_body, bool(verbose))
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\xmlrpc\client.py", line 1264, in send_request
    self.send_content(connection, request_body)
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\xmlrpc\client.py", line 1294, in send_content
    connection.endheaders(request_body)
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\http\client.py", line 834, in connect
    self.timeout, self.source_address)
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\socket.py", line 512, in create_connection
    raise err
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\socket.py", line 503, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\Scripts\behave.exe\__main__.py", line 9, in <module>
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\site-packages\behave\__main__.py", line 109, in main
    failed = runner.run()
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\site-packages\behave\runner.py", line 707, in run
    return self.run_with_paths()
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\site-packages\behave\runner.py", line 712, in run_with_paths
    self.load_hooks()
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\site-packages\behave\runner.py", line 631, in load_hooks
    exec_file(hooks_path, self.hooks)
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\site-packages\behave\runner.py", line 304, in exec_file
    exec(code, globals, locals)
  File "features\environment.py", line 5, in <module>
    from device_manager.device_management import DeviceManager
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\device_manager\device_management.py", line 7, in <module>
    import ldtp
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\__init__.py", line 598, in <module>
    _populateNamespace(globals())
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\__init__.py", line 243, in _populateNamespace
    for method in client._client.system.listMethods():
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\xmlrpc\client.py", line 1098, in __call__
    return self.__send(self.__name, args)
  File "C:\Users\jsleeper\Documents\Git repos\test_framework\tools\Python3\lib\xmlrpc\client.py", line 1437, in __request
    verbose=self.__verbose
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\client.py", line 159, in request
    if ((_ldtp_windows_env and e[0] == 10061) or \
TypeError: 'ConnectionRefusedError' object is not subscriptable
```

For the record I'm only using LDTP locally right now.
Suggestions?

**Comment by luisschoueri** [comment]
Hi @joshsleeper, 
Did you manage to solve it?
I've come accross the same issue.

Thanks!

**Comment by joshsleeper** [comment]
nope, just closing out old issues that no longer matter to me and never got any traction/response 😅

if this is an issue you still want a resolution to I strongly suggest filing a new issue.
