### ISSUE TITLE
4.0 is broken on Win10

### ISSUE THREAD

**Issue by kozmaz87** [ldtp/cobra#42]
Is this project alive and well? It looks abandoned to me but correct me if I am wrong. Anyhow. Windows 10 x64 got the client running despite the lacking instructions on how to. So it now listens and ldtp gets imported correctly however the moment the first command is issued it looks like a protocol violation to me.

```
# python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldtp
>>> ldtp.launchapp('notepad')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\__init__.py", line 416, in launchapp
    return _remote_launchapp(cmd, args, delay, env, lang)
  File "C:\Program Files (x86)\VMware\CobraWinLDTP\ldtp\client.py", line 71, in __call__
    for k, v in kwargs.items()])))
TypeError: unsupported operand type(s) for +: 'map' and 'list'
```

**Comment by kozmaz87** [comment]
FFS this is a botched log line for debug... yikes...

**Comment by rrzaripov** [comment]
@kozmaz87 we using it on Windows 10 every day, but not for app launch. I will check scenario described in your issue and make you know about results.
